exam/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.contrib import photo_upload
from django.views.generic import TemplateView
from register.views import *
from livertc.views import *
from test_management import views
from register.views import *
from Landingpage.views import (landingpage)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
# from register import views
# from capture.views import (PersonaCreateView, SaveImage, template)
from test_management import urls as test_management_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^login/$',login_view,name="login"),
    # sokmeng
    url(r'^logout/$',logout_view,name="logout"),
    # 
    url(r'^register/$',register,name="register"),
    url(r'^upload/', upload_file, name="upload"),
    url(r'^livertc/', livertc, name="livertc"),
    url(r'^save_image/(?P<cedula>\d+)/$',view=SaveImage.as_view(),name='salvar_imagen'),
    url(r'^candidate/', candidate, name="candidate"),
    # url(r'^template/', template, name="template"),
    url(r'^model_form_upload/$', model_form_upload, name="model_form_upload"),
    # url(r'^landingpage/', landingpage, name="landingpage"),
    url(r'^edit_candidate/',edit_candidate, name='edit_candidate'),
    url(r'^delete_candidate/',delete_candidate, name='delete_candidate'),
    url(r'^video_upload/',video_upload, name='video_upload'),
    url(r'^submit_answer/',submit_answer, name='submit_answer'),
    url(r'^', include(test_management_urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

livertc/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

test_management/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime

# # Create your models here.
ANSWER = (
    ('T','True'),
    ('F','False'),
)

QUESTION_TYPE = (
    ('QCM', 'Multiple Choice'),
    ('ES','Essay'),
)

class Test(models.Model):
    test_name = models.TextField(max_length=45)
    test_type = models.TextField(max_length=45)
    test_date = models.DateField()
    create_date = models.DateTimeField(auto_now_add=True)

    def add_test(self, **kwargs):
        test_obj = Test()
        test_date = datetime.strptime(kwargs["test_date"], '%m/%d/%Y').date()
        test_obj.test_name = kwargs["test_name"]
        test_obj.test_type = kwargs["test_type"]
        test_obj.test_date = test_date
        test_obj.save() 
        test_id = test_obj.id
        return test_id
    
    def __str__(self):
        return self.test_name.encode('utf8')

class Question(models.Model):
    
    test_id = models.ForeignKey('Test', on_delete=models.CASCADE)
    question_type = models.CharField(max_length=3, choices=QUESTION_TYPE, default='QCM')
    question_name = models.TextField(max_length=250)
    img_option = models.FileField(upload_to='question_img', blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)

    def add_question(self, test_id, **kwargs):
        question_obj = Question()
        question_obj.test_id = Test.objects.get(id = test_id)
        question_obj.question_type = kwargs['question_type']
        question_obj.question_name = kwargs['question_name']
        try:
            question_obj.img_option = kwargs['question_img']
        finally:
            question_obj.save()

            question_id = question_obj.id
            option_context = {
                        "option":kwargs['option'],
                        "answer":kwargs['answer']
                    }
            if kwargs['question_type'] == "QCM":
                option = Option()
                option.add_option(question_id, **option_context)
            return question_id

    def edit_question(self, row_id):
        question_obj = Question.objects.get(id = row_id)
        option_obj = Option()
        option = option_obj.edit_option(question_obj.id)
        question = {}
        question['test_id'] = question_obj.test_id.id
        question['test_name'] = question_obj.test_id.test_name
        question['question_type'] = question_obj.question_type
        question['question_name'] = question_obj.question_name
        try:
            question['img_option'] = question_obj.img_option
        except Exception as e:
            print e
        if question['question_type'] == 'QCM':
            return question, option
        else:
            return question, None
    
    def edit_question_save(self, row_id, *args, **kwargs):
        test_id = Test.objects.get(id = int(kwargs['test_id']))
        question_obj = Question.objects.get(id = row_id)
        question_obj.test_id = test_id
        question_obj.question_type = kwargs['question_type']
        question_obj.question_name = kwargs['question_name']
        if kwargs['question_img']:
            question_obj.img_option = kwargs['question_img']
        question_obj.save()
        ###Add condition for type 'QCM'
        if kwargs['option_imgs']:
            kwargs = {"options":kwargs['option_rows'], "option_imgs":kwargs['option_imgs']}
        else:
            kwargs = {"options":kwargs['option_rows']}
        option_obj = Option()
        option_obj.edit_option_save(row_id, **kwargs)
        return None   

    def __str__(self):
        return self.question_name.encode('utf8')

class Option(models.Model):
    question_id = models.ForeignKey('Question', on_delete=models.CASCADE)
    option_name = models.TextField(max_length=150, blank=True, null=True)
    answer = models.CharField(max_length=1, choices=ANSWER, default='F')
    img_option = models.FileField(upload_to='option_img', blank=True, null=True)
    last_update_date = models.DateTimeField(auto_now_add=True)

    def add_option(self, question_id, **kwargs):
        if kwargs['answer'] == 't' or kwargs['answer'] == 'T':
            choice = 'T'
        else:
            choice = 'F'
        option_obj = Option()
        option_obj.question_id = Question.objects.get(id = question_id)
        option_obj.option_name = kwargs['option']
        option_obj.answer = choice
        option_obj.save()
        return None

    def edit_option(self, question_id):
        options = Option.objects.filter(question_id = question_id)
        if options != None:
            option = []
            for obj in Option.objects.all():
                if obj.question_id.id == question_id:
                    option.append(obj)
            return option
        else:
            return None
    
    def edit_option_save(self, question_id, **kwargs):
        Option.objects.filter(question_id = question_id).delete()
        options = kwargs['options']
        try:
            option_imgs = kwargs['option_imgs']
        except Exception as ex:
            print ex

        for index, option in enumerate(options, start=0):
            option_obj = Option()
            option_obj.question_id = Question.objects.get(id = question_id)
            option_obj.option_name = options[index]["option_name"]
            option_obj.answer = options[index]["answer"]
            try:
                option_obj.img_option = option_imgs[index]
            except Exception as ex:
                print(ex)
            finally:
                option_obj.save()
        return None

    def __str__(self):
        return self.option_name.encode('utf8')

class Admin(models.Model):
    admin_name = models.TextField(max_length=45)

class Candidate(models.Model):
    candidate_name = models.TextField(max_length=45)

livertc/views.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url="/login/")
def livertc(request):
    return render(request, 'livertc.html')

templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>
    {% block title %}
    Online Examination System
    {% endblock title %}
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link rel='stylesheet' href="{% static 'css/material-kit.css' %}">
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link rel='stylesheet' href="{% static 'demo/demo.css' %}">
  <link rel='stylesheet' href="{% static 'css/register.css' %}">
  <!-- <link href="../assets/demo/demo.css" rel="stylesheet" /> -->
</head>

<body>
	
</body>
	
</html>

templates/congratulation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
  {% block extra_css %}
  <!-- Primero, incluir la libreria de JpegCam -->
  <script src="/static/jpegcam/webcam.js"></script>
  {% endblock extra_css %}
  	<link rel="apple-touch-icon" sizes="76x76" href="../static/img/apple-icon.png">
  	<link rel="icon" type="image/png" href="../static/img/kit-11.png">
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta http-equiv="cache-control" content="max-age=0" />
	<meta http-equiv="cache-control" content="no-cache" />
	<meta http-equiv="expires" content="0" />
	<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
	<meta http-equiv="pragma" content="no-cache" /> -->
  <title>
    {% block title %}
    Online Examination System
    {% endblock title %}
  </title>
  <style>
    h1 {
      font-size: 2em;
      font-weight: bold;
      color: #777777;
      text-align: center
    }
    table {
      margin: auto;
    }
    input[type=submit] {
    width: 45%;
    background-color: #04043E;
    color: white;
    padding: 11px 0px;
    margin-bottom: 30px;
    /*margin: 8px 0;*/
    border: none;
    /*margin-left: 200px;*/
    border-radius: 4px;
    cursor: pointer;
}

input[type=submit]:hover {
    background-color: green;
}
  </style>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link rel='stylesheet' href="{% static 'css/material-kit.css' %}">
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link rel='stylesheet' href="{% static 'demo/demo.css' %}">
  <!-- <link rel='stylesheet' href="{% static 'css/register.css' %}"> -->
  <!-- <link href="../assets/demo/demo.css" rel="stylesheet" /> -->

</head>

<body class="signup-page sidebar-collapse">
{% block content %}
<nav class="navbar navbar-expand-lg bg-rose">
  <img src="../static/img/kit-11.png" style="height: 70px; margin-left: 25px;">
    <div class="form-group col-md-9">
        <h3 class="card-title text-center" style="color: white; width: 100%;"><b>ONLINE EXAMINATION SYSTEM</b></h3>
        </div>
    </div>
</nav>

<div class="page-header header-filter" filter-color="purple" style="background-image: url('../static/img/kit.jpg')">
  <div class="page-header header-filter" filter-color="purple" >
    <div class="container">
        <div class="center">
          <div class="card card-signup center">
            {% if messages %}
              {% for message in messages %}
                {% if message.tags == 'success' %}
                  <h2 class="card-title text-center">Registration Completed!</h2>
                  <h5 class="card-subtitle  mb-2 text-muted" style="padding-top: 20px; padding-left: 10px; padding-right: 10px;">We are looking forward to have you join our institute. Please <a href="#">download KIT entrance exam</a> software. To take the test, install the software into your computer.
                  </h5>
                  
                  <h5 class="card-subtitle  mb-2 text-muted" style="padding-top: 20px; padding-left: 10px; padding-right: 10px;">
                    <div class="text-center">
                                        
                      To take the test, please check the <b>PASSWORD</b> to login that has been sent to <b>{{context.email}}</b>. If you cannot find the password in the <b>Inbox</b>, please check your <b>Spam box</b>.
                      </div>

                  </h5>


                  <h5 class="card-subtitle mb-2 text-muted" style="padding-top: 20px; padding-left: 10px; padding-right: 10px;">Note: the computer is required to have webcam. Please also ensures stable internet connection when taking the test.</h5>
                {% elif message.tags == 'error' %}
                  <h2 class="card-title text-center">Registration Failed!!</h2>
                  <h5 class="card-subtitle text-center mb-2 text-muted" style="padding-top: 20px; padding-left: 10px; padding-right: 10px;">Your email is already registered. You can only register for the exam once!</h5>
                {% endif %}
              {% endfor %}  
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}
	{% block extra_js %}
  <!-- Code to handle the server response -->
    <script src="{% static 'js/core/jquery.min.js' %}"></script>
    <script src="{% static 'js/core/popper.min.js' %}"></script>
    <script src="{% static 'js/core/bootstrap-material-design.min.js' %}"></script>
    <script language="JavaScript">

    </script>
{% endblock extra_js %}
</body>
</html>

templates/question_list.html
{% extends 'navigation_bar.html'%}

{% block question_list %}
<!-- sokmeng -->
   <!--  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Flamenco" rel="stylesheet">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
    <!--  -->
<nav class="navbar navbar-expand-lg bg-rose"><!--navbar navbar-expand-lg bg-rose-->
    <img src="../static/img/kit-11.png" style="width: 8%; margin-left: 25px;">
    <div class="container">
        <div class="navbar-translate">
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation" style="margin-right: 20px">
                <!-- <span class="sr-only">Toggle navigation</span> -->
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>

            </button>

        </div>
        <div class="collapse navbar-collapse" style="margin-left: 185px;> <!--style="margin-left: 100px;"-->
            <ul class="navbar-nav "><!-- ml-auto -->
                <li class="nav-item">
                    <a href="{% url 'register' %}" class=" nav-link"><b>Dashboard</b>
                </a>
                </li>
                <li class="nav-item active">
                    <a href="{% url 'question' %}" class="nav-link"><b>Question</b></a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'test' %}" class="nav-link"><b>Test</b></a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'candidate' %}" class="nav-link"><b>Candidate</b></a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'livertc' %}" class="nav-link"><b>Live Streaming</b></a>
                </li>
                <li class="nav-item">
                    <a href="#report" class="nav-link"><b>Reporting</b></a>
                </li>
                 <!-- sokmeng -->
                <li class="nav-item">
                  <form class="Logout-link" action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success" style="margin-left:120px">Logout</button> 
                  </form>  
              </li>
              <!--  -->
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <center><h2><b><u>Question List</u></b></h2></center>
</div>
<div id="inline-toolbar">
    <button class="btn btn-round btn-primary import-btn-question" data-toggle="modal" data-target="#importModal">
    <i class="material-icons" >import_export</i>   Import
    </button>
<button class="btn btn-round btn-primary add-btn-question" data-toggle="modal" data-target="#addModal">
<i class="material-icons" >add_circle</i>   Add
</button>
    <button class="btn btn-round btn-danger delete-btn-question" data-toggle="modal">
<i class="material-icons" action >delete</i>   Delete
</button>
</div>
<div class="table-container">
    <div class="table-responsive">
        <table id="fresh-table" class="table table-striped question-list table-hover table-sm">
                <thead style="background-color:#006699">
                    <tr>
                        <th scope="col">
                            <div class="form-check">
                                <label class="form-check-label" style="margin-right: 40px">
                                <input class="form-check-input check-ele check-prevent" id="checkall" type="checkbox" value="">
                                <span class="form-check-sign" >
                                    <span class="check"></span>
                                </span>
                                </label>
                            </div>
                        </th>
                        <th scope="col" style="padding-bottom: 10px;color:#fff">#</th>
                        <th scope="col" style="padding-bottom: 10px;color:#fff">Question</th>
                        <th scope="col" style="padding-bottom: 10px; color:#fff">Type</th>
                        <th scope="col" style="padding-bottom: 10px;color:#fff">Test</th>
                    </tr>
                </thead>
                <tbody>
                    {% for question in questions %}
                    <tr data-id="{{ question.id }}" class="table-row">
                        <td class="form-check">
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input check-ele check-prevent" type="checkbox" value="">
                                    <span class="form-check-sign">
                                    <span class="check"></span>
                                    </span>
                                </label>
                            </div>
                        </td>
                        <td>{{ forloop.counter }}</td>
                        <td name="question">{{ question.question_name|truncatewords:10 }}</td>
                        <td name="question_type">{{ question.get_question_type_display }}</td>
                        <td name="test_id">{{ question.test_id }}</td>  
                    </tr>      
                    {% endfor %}
                </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="addModal" tabindex="-1" role="">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="card card-signup card-plain">
                <div class="modal-body">
                    <form class="form" method="POST" action="{% url 'add_question' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h2>Add Question</h2>
                        <div class="card-body">
                            <div class="form-group">
                                <label>Test :</label>
                                <div class="input-group">
                                    {{questionForm.test_id}}
                                </div>
                            </div>
                            <div class="form-group ">
                                <label>Type :</label>
                                <div class="input-group">
                                    {{questionForm.question_type}}
                                </div>
                            </div>
                            <div class="form-group ">
                                <label>Question :</label>
                                <div class="input-group">
                                    {{questionForm.question_name}}
                                </div>
                            </div>
                                <!--used to Changed-->
                                <label>Question image:</label>
                                <div class="input-group">
                                    {{questionForm.img_option}}
                            </div>
                        <br>
                        </div>
                        <br>
                        <div>
                            <table id="fresh-table" class="table table-striped option-list table-hover table-sm">
                                <thead class="thead-table-list">
                                    <tr>
                                        <th colspan="2">Option</th>
                                        <th colspan="2">Answer</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr class="option_row rowRecord">
                                        <td>{{optionForm.option_name}}</td>
                                        <td>{{optionForm.img_option}}</td>
                                        <td>{{optionForm.answer}}</td>
                                        <td><i class="material-icons option-delete">delete</i></td>
                                    </tr>
                                    <tr class="option_row rowRecord">
                                        <td>{{optionForm.option_name}}</td>
                                        <td>{{optionForm.img_option}}</td>
                                        <td>{{optionForm.answer}}</td>
                                        <td><i class="material-icons option-delete">delete</i></td>
                                    </tr>
                                    <tr class="option_row rowRecord">
                                        <td>{{optionForm.option_name}}</td>
                                        <td>{{optionForm.img_option}}</td>
                                        <td>{{optionForm.answer}}</td>
                                        <td><i class="material-icons option-delete">delete</i></td>
                                    </tr>
                                    <tr class="option_row rowRecord">
                                        <td>{{optionForm.option_name}}</td>
                                        <td>{{optionForm.img_option}}</td>
                                        <td>{{optionForm.answer}}</td>
                                        <td><i class="material-icons option-delete">delete</i></td>
                                    </tr>
                                    <tr>
                                        <td colspan="4"><u id="add_option" class="add_option">Add New</u></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="modal-footer justify-content-right">
                            <button type="button" class="btn btn-primary btn-link btn-wd btn-lg cancel-btn-question" data-dismiss="modal">Cancel</button>
                            <button type="button" class="btn btn-primary btn-link btn-wd btn-lg submit-btn-question" name="add_new">Add & New</button>
                            <button type="button" class="btn btn-primary submit-btn-question" name="add">Add</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="editModal" tabindex="-1" role="">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="card card-signup card-plain">
                <div class="modal-body">
                    <form class="form" method="POST" action="{% url 'edit_test' %}">
                        {% csrf_token %}
                        <h2>Edit Question</h2>
                        <div id="edit_form" class="card-body">
                            <br>
                            <div class="option-list">
                                <table id="fresh-table" class="table table-striped table-hover table-sm option-list-add">
                                    <thead class="thead-table-list">
                                        <tr>
                                            <th colspan="2">Option</th>
                                            <th colspan="2">Answer</th>
                                        </tr>
                                    </thead>
                                    <tbody id="option-list-edit-body">
                                    
                                    </tbody>    
                                </table>
                                <u id="add_option" class="add_option">Add New</u>
                            </div>  
                        </div>
                        <div class="modal-footer justify-content-right">
                            <button type="button" class="btn btn-primary btn-link btn-wd btn-lg cancel-btn-question" data-dismiss="modal">Cancel</button>
                            <button type="button" class="btn btn-primary save-btn-question" name="save">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="importModal" tabindex="-1" role="">
    <div class="modal-dialog modal-login" role="document">
        <div class="modal-content">
            <div class="card card-signup card-plain">
                <div class="modal-body">
                    <form class="form" method="POST" action="{% url 'import_question' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h2>Import Question</h2>
                        <label id="import_question_sample">Get a sample file</label>
                        <hr>
                        <label for="exampleFormControlFile1">Upload question file (*.xlsx)</label>
                        <input type="file" class="form-control-file" id="exampleFormControlFile1" name="spreadsheet_file" accept=".xlsx">
                        <div class="modal-footer justify-content-right">
                            <button type="button" class="btn btn-primary btn-link btn-wd btn-lg cancel-btn-import" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary save-btn-import" name="save">Import</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/upload.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>Upload Photo</title>
	<style>
    h1 {
      font-size: 2em;
      font-weight: bold;
      color: #777777;
      text-align: center
    }
    table {
      margin: auto;
    }
  </style>
</head>
<body>
{% block content %}
<h1>
	{{what}}
</h1>
<table>
<tr>
<td>
<form action="{% url 'upload' %}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
<input type="file" name="file"/>
	<br/>
<input type="submit" name="" value="Upload Now"/>
</form>
</td>
</tr>
</table>

{% endblock content %}
</body>
</html>